[build]
  command = "npx nx build quetzaltic-ui --prod"
  publish = "dist/apps/quetzaltic-ui/browser"

[[redirects]]
  from = "/api/*"
  to = "https://soporte2.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
