[[redirects]]
  from = "/api/*"
  # IMPORTANTE: Reemplaza esto con la URL pública de tu API (ej. https://api.quetzal.com)
  to = "http://localhost:3333/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
